name: Deploy to GitHub Pages

on:
  push:
    branches: ["test"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Official OpenCV.js
        run: |
          mkdir -p lib
          curl -L https://docs.opencv.org/4.x/opencv.js -o lib/opencv.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4